import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#135bec",
        "background-light": "#f6f6f8",
        "background-dark": "#101622",
        "tertiary-fixed": "#d0e4ff",
        "surface-bright": "#f9f9f9",
        "tertiary-container": "#059eff",
        "outline": "#8e7164",
        "secondary": "#5f5e61",
        "on-primary-fixed-variant": "#7a3000",
        "primary-fixed-dim": "#ffb693",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#001d35",
        "on-surface": "#1a1c1c",
        "surface-variant": "#e2e2e2",
        "surface-dim": "#dadada",
        "brutalist-black": "#060608",
        "vibrant-orange": "#FF6B00",
        "on-surface-variant": "#5a4136",
        "pure-white": "#FFFFFF",
        "surface": "#f9f9f9",
        "tertiary-fixed-dim": "#9ccaff",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e8e8e8",
        "on-background": "#1a1c1c",
        "inverse-on-surface": "#f0f1f1",
        "surface-container": "#eeeeee",
        "inverse-surface": "#2f3131",
        "on-tertiary-container": "#003357",
        "secondary-fixed-dim": "#c8c5c9",
        "secondary-fixed": "#e5e1e5",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#00497b",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#351000",
        "on-secondary-fixed-variant": "#474649",
        "primary-fixed": "#ffdbcc",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e2e2e2",
        "on-secondary-container": "#656467",
        "on-error-container": "#93000a",
        "surface-tint": "#a04100",
        "on-secondary-fixed": "#1c1b1e",
        "tertiary": "#0062a1",
        "inverse-primary": "#ffb693",
        "on-primary-container": "#572000",
        "background": "#f9f9f9",
        "error": "#ba1a1a",
        "secondary-container": "#e5e1e5",
        "primary-container": "#ff6b00",
        "surface-container-low": "#f3f3f4",
        "outline-variant": "#e2bfb0"
      },
      fontFamily: {
        "display": ["Fjalla One", "sans-serif"],
        "body": ["Instrument Serif", "serif"],
        "serif": ["Instrument Serif", "serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Space Grotesk", "sans-serif"],
        "display-lg": ["Space Grotesk", "sans-serif"],
        "headline-xl-mobile": ["Space Grotesk", "sans-serif"],
        "headline-xl": ["Space Grotesk", "sans-serif"],
        "label-mono": ["Space Mono", "monospace"],
        "body-sm": ["Space Grotesk", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["32px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "display-lg": ["80px", { "lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "700" }],
        "headline-xl-mobile": ["40px", { "lineHeight": "1.1", "fontWeight": "700" }],
        "headline-xl": ["56px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-mono": ["12px", { "lineHeight": "1", "fontWeight": "500" }],
        "body-sm": ["14px", { "lineHeight": "1.4", "fontWeight": "400" }]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "sticker-offset": "-12px",
        "block-gap": "4rem",
        "gutter": "1.5rem",
        "grid-margin": "2rem"
      },
    },
  },
  plugins: [
    forms,
    containerQueries,
  ],
}
